### PR TITLE
Replaces occurs in, preceded by

### LINKED ISSUE #3565: MP using wrong occurs in
- [ ] Need to replace with BFO:66
- [ ] Add qc check to prevent from happening again

### PR DESCRIPTION
**Pull request by matentzn**
fixes #3565

### CODE REVIEW

**Comment by sbello** [comment]
Looking into why the checks are failing. Reports lists 31 unsatisfiable classes.
 unsatisfiable: http://purl.obolibrary.org/obo/MP_0012093
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0000423
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0008933
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0012016
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0004381
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0005071
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0005072
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0030965
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0012239
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0030966
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0030963
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0030964
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0014143
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0012320
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0013197
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0014142
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0009554
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0009555
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0000394
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0004131
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0004132
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0011058
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0012027
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0006371
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0013830
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0006370
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0011056
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0011057
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0011998
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0011830
ERROR     unsatisfiable: http://purl.obolibrary.org/obo/MP_0013799

**Comment by sbello** [comment]
Looking at MP:0008933 eq is 
'has part' some 
    (functionality
     and ('characteristic of' some 
        ('motile cilium'
         and ('occurs in' some 'primitive knot')))
     and ('has modifier' some abnormal))
running the reasoner adds the owl:nothing subclass so the eq is incorrect.
Now to figure out what is wrong with the eq :)

**Comment by matentzn** [comment]
Yes, `motile cilium` is a "cellular component", not a process. Ocurs in can only be used with processes! Will you fix these?

**Comment by matentzn** [comment]
I could fix it with Sparql, but probably you will be faster to do the 30 manually..

**Comment by sbello** [comment]
Working on fixing these now. In some cases I'm going to have to kick the eq entirely. We may need to discuss at UPheno at some point. 
Example
EQ for abnormal brain ependyma motile cilium location or orientation (MP:0030963) eq is trying to capture a cellular component that is part of a specific cell and that the cell is found in the brain. Changing the occurs in to part of does not help. I'm guessing you are not allowed to have a double part of?
'has part' some 
    (position
     and ('characteristic of' some 
        ('motile cilium'
         and ('part of' some 
            ('ependymal cell'
             and ('part of' some brain)))))
     and ('has modifier' some abnormal))

**Comment by matentzn** [comment]
this should be fine! double part of should be no problem at all..

**Comment by sbello** [comment]
I think the issue was the parent still had a bad eq and I missed that. Good to know the double part of's are safe

**Comment by sbello** [comment]
Not sure what the issue with this one is 'delayed hair regrowth' (MP:0000423)
'has part' some 
    (delayed
     and ('preceded by' some catagen)
     and ('characteristic of' some anagen)
     and ('has modifier' some abnormal))

Will just remove it for now.

**Review by sbello — COMMENTED** [review]
all good

**Pull request merged**
