### PR TITLE
Remove unused SubClassOf axioms from MP

### PR DESCRIPTION
**Pull request by matentzn**
@sbello maybe double-check this in Protege once.

### CODE REVIEW

**Comment by matentzn** [comment]
Also currently causing the build to fail!

**Comment by sbello** [comment]
@matentzn Why would these suddenly start causing the build to fail? The build was successful on the 21st. Anyway, I'll look at this now.

**Comment by matentzn** [comment]
Because they are obsolete! You cant have a subclass of axiom on an obsolete term!

**Review by sbello — APPROVED** [review]

**Comment by sbello** [comment]
Now that I looked at it I see what you are talking about and wonder how that ever got through! Merged and thanks.

**Pull request merged**
